"use client";
import {useEffect,useState} from "react";
import {BarChart3,Loader2,Target,TrendingUp} from "lucide-react";
import AppShell from "@/components/AppShell";

export default function AnalyticsPage(){
 const[data,setData]=useState<any>(null);const[error,setError]=useState("");
 useEffect(()=>{fetch("/api/analytics").then(r=>r.json()).then(x=>x.error?setError(x.error):setData(x)).catch(()=>setError("Unable to load analytics."))},[]);
 if(error)return <AppShell><div className="page"><div className="card empty"><h2>Analytics unavailable</h2><p>{error}</p></div></div></AppShell>;
 if(!data)return <AppShell><div className="page"><div className="card loading-card"><Loader2 className="spin"/>Loading analytics…</div></div></AppShell>;
 const attempts=data.attempts||[];const subjects=data.subjects||[];
 return <AppShell><div className="page workspace"><div className="page-header"><div><div className="eyebrow">PERFORMANCE</div><h1>Your progress.</h1><p>See score trends and recommended practice areas from your real attempts.</p></div></div><div className="analytics-grid"><section className="card analytics-card"><div className="section-heading"><div><h2>Score trend</h2><p>Recent completed quizzes.</p></div><TrendingUp/></div>{attempts.length?<div className="score-bars">{attempts.slice(-12).map((a:any)=><div className="score-bar-item" key={a.id}><div className="score-bar" style={{height:Math.max(8,Number(a.percentage||0))+"%"}}/><span>{Number(a.percentage||0)}%</span></div>)}</div>:<div className="empty small-empty"><BarChart3/><p>Complete quizzes to build your score trend.</p></div>}</section><section className="card analytics-card"><div className="section-heading"><div><h2>Subject performance</h2><p>Average score by subject.</p></div><Target/></div>{subjects.length?subjects.map((x:any)=><div className="subject-meter" key={x.subject}><div><b>{x.subject}</b><span>{x.average}%</span></div><div className="meter"><i style={{width:Math.min(100,x.average)+"%"}}/></div>):<div className="empty small-empty"><p>Subject data will appear after your first quiz.</p></div>}</section></div><section className="card analytics-card"><h2>Recommended Practice</h2><p>Supportive recommendations based on recent subject averages.</p><div className="recommend-grid">{subjects.filter((x:any)=>x.average<75).slice(0,4).map((x:any)=><div className="recommend-card" key={x.subject}><b>{x.subject}</b><span>{x.average}% recent average</span><a href={"/practice?topic="+encodeURIComponent(x.subject)}>Practice now →</a></div>)}{!subjects.some((x:any)=>x.average<75)&&<div className="empty small-empty"><p>No priority practice areas yet. Keep building your baseline.</p></div>}</div></section></div></AppShell>;
}
