"use client";
import {FormEvent,useEffect,useState} from "react";
import {CheckCircle2,Loader2,Save,UserRound} from "lucide-react";
import AppShell from "@/components/AppShell";

export default function ProfilePage(){
 const[p,setP]=useState<any>({full_name:"",email:"",college:"",course:"",semester:"",department:"",student_id:"",theme:"system",notifications_enabled:true});
 const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");
 useEffect(()=>{fetch("/api/profile").then(r=>r.json()).then(x=>x.profile?setP({...x.profile,email:x.email}):setError(x.error||"Unable to load profile.")).catch(()=>setError("Unable to load profile.")).finally(()=>setLoading(false))},[]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");setError("");const r=await fetch("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});const x=await r.json();if(!r.ok)setError(x.error||"Save failed.");else{setP({...x.profile,email:p.email});setMessage("Profile saved.");}setSaving(false)}
 if(loading)return <AppShell><div className="page"><div className="card loading-card"><Loader2 className="spin"/>Loading profile…</div></div></AppShell>;
 return <AppShell><div className="page workspace"><div className="page-header"><div><div className="eyebrow">ACCOUNT</div><h1>Your profile.</h1><p>Keep your academic details current for a personalized study workspace.</p></div></div><form className="card profile-card" onSubmit={submit}><div className="profile-avatar"><UserRound size={28}/></div><div className="profile-grid"><label>Full name<input value={p.full_name||""} onChange={e=>setP({...p,full_name:e.target.value})}/></label><label>Email<input value={p.email||""} disabled/></label><label>College / University<input value={p.college||""} onChange={e=>setP({...p,college:e.target.value})}/></label><label>Student ID / Roll Number<input value={p.student_id||""} onChange={e=>setP({...p,student_id:e.target.value})}/></label><label>Course / Program<input value={p.course||""} onChange={e=>setP({...p,course:e.target.value})}/></label><label>Department<input value={p.department||""} onChange={e=>setP({...p,department:e.target.value})}/></label><label>Semester<input value={p.semester||""} onChange={e=>setP({...p,semester:e.target.value})}/></label><label>Theme<select value={p.theme||"system"} onChange={e=>setP({...p,theme:e.target.value})}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label></div>{error&&<div className="error">{error}</div>}{message&&<div className="success"><CheckCircle2 size={15}/>{message}</div>}<button className="button" disabled={saving}>{saving?<><Loader2 size={16} className="spin"/>Saving…</>:<><Save size={16}/>Save profile</>}</button></form></div></AppShell>;
}
